Repository Indayvidual/Indayvidual-Server, pull requests merged in 2025-07, with the labels that each got.

#2 [CHORE] 프로젝트 세팅 및 API 응답 통일 #1
  .gitattributes
  .gitignore
  HELP.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/indayvidual/server/IndayvidualServerApplication.java
  src/main/java/com/indayvidual/server/common/BaseEntity.java
  src/main/java/com/indayvidual/server/domain/temp/controller/TempController.java
  src/main/java/com/indayvidual/server/domain/temp/converter/TempConverter.java
  src/main/java/com/indayvidual/server/domain/temp/dto/TempRequestDTO.java
  src/main/java/com/indayvidual/server/domain/temp/dto/TempResponseDTO.java
  src/main/java/com/indayvidual/server/domain/temp/entity/Temp.java
  src/main/java/com/indayvidual/server/domain/temp/entity/enums/TempStatus.java
  src/main/java/com/indayvidual/server/domain/temp/repository/TempRepository.java
  src/main/java/com/indayvidual/server/domain/temp/service/TempCommandService.java
  src/main/java/com/indayvidual/server/domain/temp/service/TempCommandServiceImpl.java
  src/main/java/com/indayvidual/server/domain/temp/service/TempQueryService.java
  src/main/java/com/indayvidual/server/domain/temp/service/TempQueryServiceImpl.java
  src/main/java/com/indayvidual/server/global/api/code/BaseCode.java
  src/main/java/com/indayvidual/server/global/api/code/BaseErrorCode.java
  src/main/java/com/indayvidual/server/global/api/code/status/ErrorStatus.java
  src/main/java/com/indayvidual/server/global/api/code/status/SuccessStatus.java
  src/main/java/com/indayvidual/server/global/api/response/ApiResponse.java
  src/main/java/com/indayvidual/server/global/api/response/ErrorReasonDTO.java
  src/main/java/com/indayvidual/server/global/api/response/ReasonDTO.java
  src/main/java/com/indayvidual/server/global/config/QueryDSLConfig.java
  src/main/java/com/indayvidual/server/global/config/SwaggerConfig.java
  src/main/java/com/indayvidual/server/global/exception/ExceptionAdvice.java
  src/main/java/com/indayvidual/server/global/exception/GeneralException.java
  src/main/java/com/indayvidual/server/global/exception/handler/TempHandler.java
  src/main/resources/application.properties
  src/test/java/com/indayvidual/server/IndayvidualServerApplicationTests.java
Labels: 🧹 chore

#5 [CHORE] .gitignore에 application.yml 제외 #3
  .gitignore
  src/main/resources/application.yml
Labels: 🧹 chore

#22 Feat/#20 get calendar
  src/main/java/com/indayvidual/server/domain/calendar/controller/CalendarEventController.java
  src/main/java/com/indayvidual/server/domain/calendar/converter/EventConverter.java
  src/main/java/com/indayvidual/server/domain/calendar/dto/response/GetDayEventResponseDto.java
  src/main/java/com/indayvidual/server/domain/calendar/dto/response/GetMonthlyCalendarResponseDto.java
  src/main/java/com/indayvidual/server/domain/calendar/repository/EventRepository.java
  src/main/java/com/indayvidual/server/domain/calendar/service/EventQueryService.java
  src/main/java/com/indayvidual/server/domain/calendar/service/EventQueryServiceImpl.java
  src/main/java/com/indayvidual/server/global/api/code/status/ErrorStatus.java
  src/main/java/com/indayvidual/server/global/api/code/status/SuccessStatus.java
Labels: ✨ feature

#24 Feat/#23 timetable crud
  src/main/java/com/indayvidual/server/domain/timetable/controller/TimetableController.java
  src/main/java/com/indayvidual/server/domain/timetable/converter/TimetableConverter.java
  src/main/java/com/indayvidual/server/domain/timetable/dto/request/CreateTimetableRequestDto.java
  src/main/java/com/indayvidual/server/domain/timetable/dto/response/CreateTimetableResponseDto.java
  src/main/java/com/indayvidual/server/domain/timetable/dto/response/GetTimetableResponseDto.java
  src/main/java/com/indayvidual/server/domain/timetable/entity/Timetable.java
  src/main/java/com/indayvidual/server/domain/timetable/entity/enums/Semester.java
  src/main/java/com/indayvidual/server/domain/timetable/repository/TimetableRepository.java
  src/main/java/com/indayvidual/server/domain/timetable/service/TimetableCommandService.java
  src/main/java/com/indayvidual/server/domain/timetable/service/TimetableCommandServiceImpl.java
  src/main/java/com/indayvidual/server/domain/timetable/service/TimetableQueryService.java
  src/main/java/com/indayvidual/server/domain/timetable/service/TimetableQueryServiceImpl.java
  src/main/java/com/indayvidual/server/global/api/code/status/ErrorStatus.java
  src/main/java/com/indayvidual/server/global/api/code/status/SuccessStatus.java
Labels: ✨ feature

#28 [REFACTOR] calendar와 event 도메인 분리 #25
  src/main/java/com/indayvidual/server/domain/calendar/controller/CalendarController.java
  src/main/java/com/indayvidual/server/domain/calendar/controller/CalendarEventController.java
  src/main/java/com/indayvidual/server/domain/calendar/service/CalendarQueryService.java
  src/main/java/com/indayvidual/server/domain/calendar/service/CalendarQueryServiceImpl.java
  src/main/java/com/indayvidual/server/domain/calendar/service/EventCommandService.java
  src/main/java/com/indayvidual/server/domain/event/controller/EventController.java
  src/main/java/com/indayvidual/server/domain/event/converter/EventConverter.java
  src/main/java/com/indayvidual/server/domain/event/dto/request/CreateEventRequestDto.java
  src/main/java/com/indayvidual/server/domain/event/dto/request/UpdateEventRequestDto.java
  src/main/java/com/indayvidual/server/domain/event/dto/response/CreateEventResponseDto.java
  src/main/java/com/indayvidual/server/domain/event/dto/response/UpdateEventResponseDto.java
  src/main/java/com/indayvidual/server/domain/event/entity/Event.java
  src/main/java/com/indayvidual/server/domain/event/repository/EventRepository.java
  src/main/java/com/indayvidual/server/domain/event/service/EventCommandService.java
  src/main/java/com/indayvidual/server/domain/event/service/EventCommandServiceImpl.java
  src/main/java/com/indayvidual/server/domain/event/service/EventQueryService.java
  src/main/java/com/indayvidual/server/domain/event/service/EventQueryServiceImpl.java
Labels: ♻️ refactor

#50 [REFACTOR] 일정 관련 기능 구조 개선 #48
  src/main/java/com/indayvidual/server/domain/event/controller/EventController.java
  src/main/java/com/indayvidual/server/domain/event/converter/EventConverter.java
  src/main/java/com/indayvidual/server/domain/event/dto/request/CreateEventRequestDto.java
  src/main/java/com/indayvidual/server/domain/event/dto/request/UpdateEventRequestDto.java
  src/main/java/com/indayvidual/server/domain/event/dto/response/CreateEventResponseDto.java
  src/main/java/com/indayvidual/server/domain/event/dto/response/UpdateEventResponseDto.java
  src/main/java/com/indayvidual/server/domain/event/exception/EventException.java
  src/main/java/com/indayvidual/server/domain/event/repository/EventRepository.java
  src/main/java/com/indayvidual/server/domain/event/service/EventCommandServiceImpl.java
  src/main/java/com/indayvidual/server/domain/event/service/EventQueryServiceImpl.java
  src/main/java/com/indayvidual/server/global/api/code/status/ErrorStatus.java
Labels: ♻️ refactor

#57 Refactor/#54 calendar timetable structure
  src/main/java/com/indayvidual/server/domain/calendar/controller/CalendarController.java
  src/main/java/com/indayvidual/server/domain/calendar/dto/response/GetMonthlyCalendarResponseDto.java
  src/main/java/com/indayvidual/server/domain/calendar/exception/CalendarException.java
  src/main/java/com/indayvidual/server/domain/calendar/service/CalendarQueryService.java
  src/main/java/com/indayvidual/server/domain/calendar/service/CalendarQueryServiceImpl.java
  src/main/java/com/indayvidual/server/domain/timetable/controller/TimetableController.java
  src/main/java/com/indayvidual/server/domain/timetable/exception/TimetableException.java
  src/main/java/com/indayvidual/server/domain/timetable/service/TimetableCommandServiceImpl.java
  src/main/java/com/indayvidual/server/domain/timetable/service/TimetableQueryServiceImpl.java
  src/main/java/com/indayvidual/server/global/api/code/status/ErrorStatus.java
Labels: ♻️ refactor

#62 [FEAT] 색상 목록 조회 api 추가 #16
  src/main/java/com/indayvidual/server/domain/todo/controller/ColorController.java
  src/main/java/com/indayvidual/server/domain/todo/controller/TodoCategoryController.java
  src/main/java/com/indayvidual/server/domain/todo/controller/TodoTaskController.java
  src/main/java/com/indayvidual/server/domain/todo/converter/CategoryConverter.java
  src/main/java/com/indayvidual/server/domain/todo/converter/TaskConverter.java
  src/main/java/com/indayvidual/server/domain/todo/entity/Color.java
  src/main/java/com/indayvidual/server/domain/todo/repository/ColorRepository.java
  src/main/java/com/indayvidual/server/domain/todo/service/color/ColorQueryService.java
  src/main/java/com/indayvidual/server/global/api/code/status/SuccessStatus.java
Labels: ✨ feature

#65 [FEAT] 시간표 삭제하기 API 구현 #64
  src/main/java/com/indayvidual/server/domain/timetable/controller/TimetableController.java
  src/main/java/com/indayvidual/server/domain/timetable/service/TimetableCommandService.java
  src/main/java/com/indayvidual/server/domain/timetable/service/TimetableCommandServiceImpl.java
  src/main/java/com/indayvidual/server/global/api/code/status/ErrorStatus.java
  src/main/java/com/indayvidual/server/global/api/code/status/SuccessStatus.java
Labels: ✨ feature

#67 Feat/#66 event all day
  src/main/java/com/indayvidual/server/domain/calendar/controller/CalendarController.java
  src/main/java/com/indayvidual/server/domain/event/converter/EventConverter.java
  src/main/java/com/indayvidual/server/domain/event/dto/request/CreateEventRequestDto.java
  src/main/java/com/indayvidual/server/domain/event/dto/request/UpdateEventRequestDto.java
  src/main/java/com/indayvidual/server/domain/event/dto/response/UpdateEventResponseDto.java
  src/main/java/com/indayvidual/server/domain/event/entity/Event.java
  src/main/java/com/indayvidual/server/domain/event/service/EventCommandServiceImpl.java
Labels: ✨ feature

#69 Refactor/#68 timetable image multipart
  src/main/java/com/indayvidual/server/domain/timetable/controller/TimetableController.java
  src/main/java/com/indayvidual/server/domain/timetable/converter/TimetableConverter.java
  src/main/java/com/indayvidual/server/domain/timetable/dto/request/CreateTimetableRequestDto.java
  src/main/java/com/indayvidual/server/domain/timetable/entity/Timetable.java
  src/main/java/com/indayvidual/server/domain/timetable/service/TimetableCommandService.java
  src/main/java/com/indayvidual/server/domain/timetable/service/TimetableCommandServiceImpl.java
Labels: ♻️ refactor

#74 [REFACTOR] id 필드 추가 #70
  src/main/java/com/indayvidual/server/domain/todo/controller/ColorController.java
  src/main/java/com/indayvidual/server/domain/todo/converter/ColorConverter.java
  src/main/java/com/indayvidual/server/domain/todo/dto/response/ColorResponseDTO.java
  src/main/java/com/indayvidual/server/domain/todo/repository/ColorRepository.java
  src/main/java/com/indayvidual/server/domain/todo/service/color/ColorQueryService.java
Labels: ♻️ refactor

#77 Refactor/#63 update task order add category
  src/main/java/com/indayvidual/server/domain/todo/controller/TodoCategoryController.java
  src/main/java/com/indayvidual/server/domain/todo/controller/TodoTaskController.java
  src/main/java/com/indayvidual/server/domain/todo/dto/request/TaskOrderCategoryUpdateBulkRequestDTO.java
  src/main/java/com/indayvidual/server/domain/todo/dto/request/TaskOrderCategoryUpdateRequestDTO.java
  src/main/java/com/indayvidual/server/domain/todo/dto/request/TaskOrderUpdateRequestDTO.java
  src/main/java/com/indayvidual/server/domain/todo/dto/response/TaskOrderCategoryUpdateResponseDTO.java
  src/main/java/com/indayvidual/server/domain/todo/entity/Task.java
  src/main/java/com/indayvidual/server/domain/todo/repository/CategoryRepository.java
  src/main/java/com/indayvidual/server/domain/todo/repository/TaskRepository.java
  src/main/java/com/indayvidual/server/domain/todo/service/category/CategoryCommandService.java
  src/main/java/com/indayvidual/server/domain/todo/service/task/TaskCommandService.java
  src/main/java/com/indayvidual/server/domain/todo/service/task/TaskCommandServiceImpl.java
  src/main/java/com/indayvidual/server/domain/todo/service/task/TaskQueryServiceImpl.java
  src/main/java/com/indayvidual/server/global/api/code/status/SuccessStatus.java
Labels: ♻️ refactor
