Repository Indayvidual/Indayvidual-Server, pull requests merged in 2025-08, with the labels that each got.

#84 [REFACTOR] 캘린더, 일정 관련 API 수정: color code #83
  src/main/java/com/indayvidual/server/domain/calendar/dto/response/GetDayEventResponseDto.java
  src/main/java/com/indayvidual/server/domain/calendar/dto/response/GetMonthlyCalendarResponseDto.java
  src/main/java/com/indayvidual/server/domain/calendar/service/CalendarQueryServiceImpl.java
  src/main/java/com/indayvidual/server/domain/event/converter/EventConverter.java
  src/main/java/com/indayvidual/server/domain/event/dto/request/CreateEventRequestDto.java
  src/main/java/com/indayvidual/server/domain/event/dto/request/UpdateEventRequestDto.java
  src/main/java/com/indayvidual/server/domain/event/dto/response/UpdateEventResponseDto.java
  src/main/java/com/indayvidual/server/domain/event/entity/Event.java
  src/main/java/com/indayvidual/server/global/api/code/status/ErrorStatus.java
Labels: ♻️ refactor

#88 [REFACTOR] 컬러 조회 로직 수정 #87
  src/main/java/com/indayvidual/server/domain/todo/controller/ColorController.java
  src/main/java/com/indayvidual/server/domain/todo/converter/ColorConverter.java
  src/main/java/com/indayvidual/server/domain/todo/dto/response/ColorResponseDTO.java
  src/main/java/com/indayvidual/server/domain/todo/entity/Color.java
  src/main/java/com/indayvidual/server/domain/todo/repository/ColorRepository.java
  src/main/java/com/indayvidual/server/domain/todo/service/color/ColorQueryService.java
  src/main/java/com/indayvidual/server/domain/todo/service/color/ColorService.java
Labels: ♻️ refactor

#94 [FEAT] 특정 날짜 일정 조회 시 'isAllDay' 추가 #93
  src/main/java/com/indayvidual/server/domain/calendar/dto/response/GetDayEventResponseDto.java
  src/main/java/com/indayvidual/server/domain/event/converter/EventConverter.java
Labels: ✨ feature

#105 [FEAT] 시간표 관련 API: 학교 이름 추가 #104
  src/main/java/com/indayvidual/server/domain/timetable/controller/TimetableController.java
  src/main/java/com/indayvidual/server/domain/timetable/converter/TimetableConverter.java
  src/main/java/com/indayvidual/server/domain/timetable/dto/response/CreateTimetableResponseDto.java
  src/main/java/com/indayvidual/server/domain/timetable/dto/response/GetTimetableResponseDto.java
  src/main/java/com/indayvidual/server/domain/timetable/entity/Timetable.java
  src/main/java/com/indayvidual/server/domain/timetable/service/TimetableCommandService.java
  src/main/java/com/indayvidual/server/domain/timetable/service/TimetableCommandServiceImpl.java
Labels: ✨ feature

#108 [FIX] task 조회 메서드 수정 #107
  src/main/java/com/indayvidual/server/domain/todo/repository/TaskRepository.java
  src/main/java/com/indayvidual/server/domain/todo/service/task/TaskCommandServiceImpl.java
Labels: 🐛 bug

#110 [FIX] task 순서 변경 로직 수정 #107
  src/main/java/com/indayvidual/server/domain/todo/repository/TaskRepository.java
  src/main/java/com/indayvidual/server/domain/todo/service/task/TaskCommandServiceImpl.java
Labels: 🐛 bug

#111 [FIX] 슬롯 크기 정의 로직 수정 #107
  src/main/java/com/indayvidual/server/domain/todo/controller/TodoTaskController.java
  src/main/java/com/indayvidual/server/domain/todo/repository/TaskRepository.java
  src/main/java/com/indayvidual/server/domain/todo/service/task/TaskCommandService.java
  src/main/java/com/indayvidual/server/domain/todo/service/task/TaskCommandServiceImpl.java
Labels: 🐛 bug

#116 [FIX] 할일 날짜 수정 시 새로운 order 적용 #115
  src/main/java/com/indayvidual/server/domain/todo/service/task/TaskCommandServiceImpl.java
Labels: 🐛 bug
